#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 27 21:59:37 COT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryUnbound_r5.2.2.zip
