#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Oct 30 16:18:25 COT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.3.zip
