version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
rusticdelight = true
rehooked = true
endersdelight = true
farmersdelight = true
create_enchantment_industry = true
mcwbridges = true
deeperdarker = true
aquaculturedelight = true
sliceanddice = true
create = true
mynethersdelight = true
handcrafted = true
advancednetherite = true
vegandelight = true
easyanvils = true
sereneseasons = true
mobs_of_mythology = true
comforts = true
minecraft = true
wallfence = true
create_dragons_plus = true
